# Generated by Django 3.2 on 2021-04-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('cover', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField()),
                ('views', models.IntegerField()),
            ],
        ),
    ]
