# Generated by Django 3.2 on 2021-04-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='viewscounter',
        ),
    ]
